name: Hourly Image Generation

on:
  schedule:
    - cron: '0 16-23,0-15 * * *'  # Каждый час с 16:00 до 15:00 UTC (19:00-18:00 МСК)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Необходимо для пуша в репозиторий

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0  # Чтобы git push работал

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install gradio_client python-dotenv Pillow requests

      - name: Load environment variables
        run: |
          echo "HF_TOKEN=${{ secrets.HF_TOKEN }}" >> .env
          echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" >> .env
          echo "TELEGRAM_CHANNEL_ID=${{ secrets.TELEGRAM_CHANNEL_ID }}" >> .env

      - name: Run image generation
        run: python generate_images.py

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add input.txt
          git diff-index --quiet HEAD || git commit -m "Update input.txt after image generation"
          git push origin main